# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3 # Specify your Python version
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Make sure to use a version compatible with your ruff install
    hooks:
    -   id: ruff
        args: [--fix] # Enable auto-fixing
    -   id: ruff-format
